aot:
	flutter assemble -v -dBuildMode="release" \
		-dTargetPlatform="linux-x64" \
		--output="./build/release" release_bundle_linux-x64_assets 
	
	# cd widgets/status_bar && \
	# 	flutter assemble -v -dBuildMode="release" \
	# 	-dTargetPlatform="linux-x64" \
	# 	--output="./build/release/assets" copy_flutter_bundle


